
package login;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class add extends javax.swing.JFrame {
    String name;
    Connection con=null;
            Statement st=null;
            ResultSet rs=null;
    public add() {
        initComponents();
         show_list();
         combobox();
    }
    public ArrayList<list> Userlist(){
        ArrayList<list> UserList = new ArrayList<>();
        try
        {
            Class.forName("org.sqlite.JDBC");
             con=DriverManager.getConnection("jdbc:sqlite:personal info.sqlite");
             st=con.createStatement();
             rs=st.executeQuery("select * from user");
            list List;
            
            
            while(rs.next()){
                 List = new list 
                         (rs.getString ("firstname"), 
                         rs.getString("lastname"),
                         rs.getString("emailAdd"),
                         rs.getString("address"), 
                         rs.getInt("mobile"),
                         rs.getInt("hrs"),
                         rs.getInt("mins"));
                    UserList.add(List);
            }
             
                }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
        finally{
     try{
         st.close();
         rs.close();
     }
     catch(Exception e){
     }}

        return UserList;
    }
    public void show_list(){
    ArrayList<list> user = Userlist();
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            Object[] row = new Object [7];
           for (int i=0;i<user.size();i++){
           row[0]=user.get(i).getfirst();
           row[1]=user.get(i).getlast();
           row[2]=user.get(i).getadd();
           row[3]=user.get(i).getmobile();
           row[4]=user.get(i).getemail();
           row[5]=user.get(i).gethrs();
           row[6]=user.get(i).getmins();
           model.addRow(row);
           }
    }
        
private void combobox(){

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        add_member = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        mins = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hrs = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("members");
        setMaximumSize(new java.awt.Dimension(1011, 420));
        setMinimumSize(new java.awt.Dimension(1011, 420));
        getContentPane().setLayout(null);

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname);
        fname.setBounds(130, 20, 136, 20);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FIRST NAME:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 64, 14);

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address);
        address.setBounds(130, 80, 136, 53);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADDRESS:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 60, 14);

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        getContentPane().add(lname);
        lname.setBounds(130, 50, 136, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SURNAME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 50, 52, 14);

        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        getContentPane().add(mobile);
        mobile.setBounds(130, 150, 136, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MOBILE NUMBER:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 150, 88, 14);

        jButton1.setText("delete");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 290, 100, 39);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "firstname", "surname", "address", "mobile number", "email", "hrs", "mins"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 0, 758, 397);

        add_member.setText("add");
        add_member.setOpaque(false);
        add_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_memberActionPerformed(evt);
            }
        });
        getContentPane().add(add_member);
        add_member.setBounds(140, 290, 130, 39);

        jButton3.setText("back");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 340, 130, 39);

        mins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minsActionPerformed(evt);
            }
        });
        getContentPane().add(mins);
        mins.setBounds(130, 240, 136, 20);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MINUTES:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 240, 48, 14);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(130, 180, 136, 20);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EMAIL ADDRESS:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 180, 83, 14);

        hrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrsActionPerformed(evt);
            }
        });
        getContentPane().add(hrs);
        hrs.setBounds(130, 210, 136, 20);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HOURS:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 210, 39, 14);

        edit.setText("edit");
        edit.setOpaque(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(30, 340, 100, 39);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/414498.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 290, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try 
        {
            
           
            int row = table.getSelectedRow();
            String clicked=(table.getModel().getValueAt(row,0).toString());
            st.execute("delete from user where firstname='"+clicked+"' ");
           DefaultTableModel model =(DefaultTableModel)table.getModel();
           model.setRowCount(0);
              show_list();
              JOptionPane.showMessageDialog(rootPane,"deleted!");
              
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
    }
    finally{
     try{
         st.close();
         rs.close();
     }
     catch(Exception e){
     }} 
        //delete
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_memberActionPerformed
        // TODO add your handling code here:
     
     try 
        {
             st=con.createStatement();
                String name=fname.getText();             
                String surname=lname.getText();             
                String add= address.getText();           
                String mobile_num=mobile.getText();
                String emailadd=email.getText();
                String hours=hrs.getText();
                String minutes=mins.getText();
            st.execute("insert into user (firstname,lastname,address,mobile,emailAdd,hrs,mins)values('" + name + "','"+surname+"','"+add+"','"+mobile_num+"','"+emailadd+"','"+hours+"','"+minutes+"')");
           JOptionPane.showMessageDialog(rootPane,"added!");
              DefaultTableModel model =(DefaultTableModel)table.getModel();
              model.setRowCount(0);
              show_list();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
    }
finally{
     try{
         st.close();
         rs.close();
     }
     catch(Exception e){
     }}
    }//GEN-LAST:event_add_memberActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
               this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        try 
        {
            int row = table.getSelectedRow();
           String clicked=(table.getModel().getValueAt(row,0).toString());
             st=con.createStatement();
             rs=st.executeQuery("SELECT * FROM user where firstname='"+clicked+"'");
            if (rs.next()){
            
                String selected = rs.getString("firstname");
                fname.setText(selected);
                String selected_1 = rs.getString("lastname");
                lname.setText(selected_1);
                String selected_2 = rs.getString("address");
                address.setText(selected_2);
                String selected_3 = rs.getString("mobile");
                mobile.setText(selected_3);
                String selected_4 = rs.getString("emailAdd");
                email.setText(selected_4);
                String selected_5 = rs.getString("hrs");
                hrs.setText(selected_5);
                String selected_6 = rs.getString("mins");
                mins.setText(selected_6);
                             }
           
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
    }
    finally{
     try{
         st.close();
         rs.close();
     }
     catch(Exception e){
     }}    
    }//GEN-LAST:event_tableMouseClicked

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void minsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minsActionPerformed

    private void hrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrsActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try 
        {
             
            Class.forName("org.sqlite.JDBC");
             con=DriverManager.getConnection("jdbc:sqlite:personal info.sqlite");
             st=con.createStatement();
             int row = table.getSelectedRow();
            String clicked=(table.getModel().getValueAt(row,0).toString());
                String name=fname.getText();             
                String surname=lname.getText();             
                String add= address.getText();           
                String mobile_num=mobile.getText();
                String emailadd=email.getText();
                String hours=hrs.getText();
                String minutes=mins.getText();
             st.execute("update user set firstname='"+name+"',lastname='"+surname+"',address='"+add+"',mobile='"+mobile_num+"',emailAdd='"+emailadd+"',hrs='"+hours+"',mins='"+minutes+"' where firstname='"+clicked+"'");
           

           
                 DefaultTableModel model =(DefaultTableModel)table.getModel();
           model.setRowCount(0);
              show_list();
              JOptionPane.showMessageDialog(rootPane,"updated!");
              
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            
    }
    finally{
     try{
         st.close();
         rs.close();
     }
     catch(Exception e){
     }} 
        //edit
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_member;
    private javax.swing.JTextField address;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField hrs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mins;
    private javax.swing.JTextField mobile;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
